/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Clan {
  'id' : bigint,
  'members' : Array<Principal>,
  'name' : string,
  'createdAt' : bigint,
  'memberCount' : bigint,
  'founder' : Principal,
}
export interface CombatDetails {
  'status' : CombatStatus,
  'result' : [] | [CombatResult],
  'enemyStats' : Enemy,
  'playerStats' : Survivor,
  'rewardedCurrency' : bigint,
  'enemyHealth' : bigint,
  'rewardedExp' : bigint,
  'playerHealth' : bigint,
}
export interface CombatResult {
  'rewardCurrency' : bigint,
  'winner' : Winner,
  'rewardExp' : bigint,
}
export interface CombatStatus {
  'combatOngoing' : boolean,
  'enemyName' : string,
  'enemyHealth' : bigint,
  'playerHealth' : bigint,
  'playerActiveSurvivor' : Survivor,
}
export interface Crate {
  'id' : bigint,
  'reward' : bigint,
  'name' : string,
  'description' : string,
  'requiredKey' : string,
  'location' : string,
}
export interface Dungeon {
  'id' : bigint,
  'difficulty' : bigint,
  'name' : string,
  'description' : string,
  'availableCrates' : Array<Crate>,
  'quests' : Array<Quest>,
}
export interface Enemy {
  'magic' : bigint,
  'name' : string,
  'goldReward' : bigint,
  'expReward' : bigint,
  'speed' : bigint,
  'defense' : bigint,
  'attack' : bigint,
  'health' : bigint,
}
export interface Killer {
  'id' : bigint,
  'url' : string,
  'storyline' : [] | [string],
  'name' : string,
  'unlocked' : boolean,
  'description' : string,
  'stats' : {
    'magic' : bigint,
    'level' : bigint,
    'speed' : bigint,
    'defense' : bigint,
    'attack' : bigint,
    'health' : bigint,
  },
  'unlockCriteria' : [] | [bigint],
}
export interface Pet {
  'dropRateBonus' : bigint,
  'name' : string,
  'experienceBonus' : bigint,
  'description' : string,
  'levelBonus' : bigint,
}
export interface PlayerProfile {
  'hasAdminPanel' : boolean,
  'completedQuests' : Array<bigint>,
  'storylineProgress' : bigint,
  'activeDungeonId' : [] | [bigint],
  'inventory' : Array<string>,
  'pets' : Array<Pet>,
  'collectedKeys' : Array<string>,
  'survivors' : Array<Survivor>,
  'activeSurvivor' : [] | [Survivor],
  'currency' : bigint,
  'equippedArmor' : [] | [bigint],
  'killers' : Array<Killer>,
  'weapons' : Array<Weapon>,
  'openedCrates' : Array<bigint>,
  'equippedWeapon' : [] | [Weapon],
  'equippedPet' : [] | [Pet],
}
export interface Quest {
  'id' : bigint,
  'dungeonId' : bigint,
  'rewardCurrency' : bigint,
  'name' : string,
  'description' : string,
}
export interface Survivor {
  'name' : string,
  'level' : bigint,
  'experience' : bigint,
  'stats' : {
    'magic' : bigint,
    'level' : bigint,
    'speed' : bigint,
    'defense' : bigint,
    'attack' : bigint,
    'health' : bigint,
  },
}
export interface UserProfile {
  'hasAdminPanel' : boolean,
  'completedQuests' : Array<bigint>,
  'storylineProgress' : bigint,
  'activeDungeonId' : [] | [bigint],
  'inventory' : Array<string>,
  'pets' : Array<Pet>,
  'collectedKeys' : Array<string>,
  'survivors' : Array<Survivor>,
  'activeSurvivor' : [] | [Survivor],
  'currency' : bigint,
  'equippedArmor' : [] | [bigint],
  'killers' : Array<Killer>,
  'weapons' : Array<Weapon>,
  'openedCrates' : Array<bigint>,
  'equippedWeapon' : [] | [Weapon],
  'equippedPet' : [] | [Pet],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface Weapon {
  'name' : string,
  'defenseBonus' : bigint,
  'attackBonus' : bigint,
  'description' : string,
  'magicBonus' : bigint,
  'speedBonus' : bigint,
}
export interface WhyDontYouJoin {
  'id' : bigint,
  'active' : boolean,
  'name' : string,
  'memberCount' : bigint,
  'createClan' : boolean,
  'description' : string,
  'imageUrl' : string,
  'leader' : Principal,
}
export type Winner = { 'player' : null } |
  { 'enemy' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addPet' : ActorMethod<[Pet], undefined>,
  'addWeapon' : ActorMethod<[Weapon], undefined>,
  'addWhyDontYouJoin' : ActorMethod<[string, string, string], WhyDontYouJoin>,
  'adminGrantCurrency' : ActorMethod<[bigint], undefined>,
  'adminSetLevel' : ActorMethod<[string, bigint], undefined>,
  'adminUnlockKiller' : ActorMethod<[bigint], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'completeQuest' : ActorMethod<[bigint], undefined>,
  'createClanFromJoin' : ActorMethod<[bigint, string], [] | [Clan]>,
  'createPlayerProfile' : ActorMethod<[], PlayerProfile>,
  'createSurvivor' : ActorMethod<
    [
      string,
      {
        'magic' : bigint,
        'speed' : bigint,
        'defense' : bigint,
        'attack' : bigint,
        'health' : bigint,
      },
    ],
    undefined
  >,
  'earnCurrency' : ActorMethod<[bigint], undefined>,
  'equipPet' : ActorMethod<[string], undefined>,
  'equipWeapon' : ActorMethod<[string], undefined>,
  'getActiveDungeon' : ActorMethod<[], [] | [bigint]>,
  'getActiveDungeonMaps' : ActorMethod<[], Array<Dungeon>>,
  'getActiveWhyDontYouJoins' : ActorMethod<[], Array<WhyDontYouJoin>>,
  'getAllDungeonKeys' : ActorMethod<[], Array<string>>,
  'getAllDungeonMaps' : ActorMethod<[], Array<Dungeon>>,
  'getAllKeys' : ActorMethod<[], Array<string>>,
  'getAllWhyDontYouJoins' : ActorMethod<[], Array<WhyDontYouJoin>>,
  'getAvailableDungeonMaps' : ActorMethod<[], [] | [Array<Dungeon>]>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getClanMarketplace' : ActorMethod<[], Array<Clan>>,
  'getCollectedKeys' : ActorMethod<[], Array<string>>,
  'getCombatStatus' : ActorMethod<[], [] | [CombatStatus]>,
  'getCompletedQuests' : ActorMethod<[], Array<bigint>>,
  'getOpenedCrates' : ActorMethod<[], Array<bigint>>,
  'getPlayerInventory' : ActorMethod<[], Array<string>>,
  'getPlayerProfile' : ActorMethod<[], PlayerProfile>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'joinExistingClan' : ActorMethod<[bigint], [] | [Clan]>,
  'joinRandomClan' : ActorMethod<[], [] | [Clan]>,
  'performAttack' : ActorMethod<[Enemy], CombatDetails>,
  'performMagicAttack' : ActorMethod<[Enemy], CombatDetails>,
  'purchaseAdminPanel' : ActorMethod<[], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setActiveSurvivor' : ActorMethod<[string], undefined>,
  'startCombat' : ActorMethod<[Enemy], undefined>,
  'startQuest' : ActorMethod<[bigint], undefined>,
  'unlockCrate' : ActorMethod<[bigint], undefined>,
  'unlockNextKiller' : ActorMethod<[], undefined>,
  'updateWhyDontYouJoin' : ActorMethod<
    [bigint, boolean],
    [] | [WhyDontYouJoin]
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];