/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AdminPanelEvent {
  'id' : bigint,
  'creator' : Principal,
  'description' : string,
  'timestamp' : bigint,
  'eventName' : string,
}
export interface Announcement {
  'id' : bigint,
  'title' : string,
  'createdBy' : Principal,
  'message' : string,
  'timestamp' : bigint,
}
export interface Bot {
  'id' : bigint,
  'url' : string,
  'rewardCurrency' : bigint,
  'difficulty' : bigint,
  'name' : string,
  'description' : string,
  'rewardExp' : bigint,
}
export interface BotCombatStatus {
  'combatOngoing' : boolean,
  'botName' : string,
  'botHealth' : bigint,
  'botId' : bigint,
  'playerHealth' : bigint,
  'playerActiveSurvivor' : Survivor,
}
export type ItemType = { 'key' : null } |
  { 'pet' : null } |
  { 'armor' : null } |
  { 'misc' : null } |
  { 'currencyPack' : null } |
  { 'weapon' : null };
export interface Killer {
  'id' : bigint,
  'url' : string,
  'storyline' : [] | [string],
  'name' : string,
  'unlocked' : boolean,
  'description' : string,
  'stats' : {
    'magic' : bigint,
    'level' : bigint,
    'speed' : bigint,
    'defense' : bigint,
    'attack' : bigint,
    'health' : bigint,
  },
  'unlockCriteria' : [] | [bigint],
}
export interface Pet {
  'dropRateBonus' : bigint,
  'name' : string,
  'experienceBonus' : bigint,
  'description' : string,
  'levelBonus' : bigint,
}
export interface ShopItem {
  'id' : bigint,
  'name' : string,
  'description' : string,
  'bonusStat' : [] | [Stat],
  'itemType' : ItemType,
  'price' : bigint,
}
export type Stat = { 'magic' : bigint } |
  { 'level' : bigint } |
  { 'experience' : bigint } |
  { 'speed' : bigint } |
  { 'defense' : bigint } |
  { 'attack' : bigint } |
  { 'health' : bigint };
export interface Survivor {
  'name' : string,
  'level' : bigint,
  'experience' : bigint,
  'stats' : {
    'magic' : bigint,
    'level' : bigint,
    'speed' : bigint,
    'defense' : bigint,
    'attack' : bigint,
    'health' : bigint,
  },
}
export interface UserProfile {
  'rebirthCount' : bigint,
  'hasAdminPanel' : boolean,
  'username' : string,
  'completedQuests' : Array<bigint>,
  'storylineProgress' : bigint,
  'activeDungeonId' : [] | [bigint],
  'inventory' : Array<string>,
  'pets' : Array<Pet>,
  'collectedKeys' : Array<string>,
  'survivors' : Array<Survivor>,
  'auraLevel' : bigint,
  'activeSurvivor' : [] | [Survivor],
  'currency' : bigint,
  'auraPower' : bigint,
  'equippedArmor' : [] | [bigint],
  'killers' : Array<Killer>,
  'weapons' : Array<Weapon>,
  'openedCrates' : Array<bigint>,
  'equippedWeapon' : [] | [Weapon],
  'rebirthMultiplier' : bigint,
  'equippedPet' : [] | [Pet],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export type UsernameUpdateResult = { 'alreadyTaken' : null } |
  { 'createdUsername' : string } |
  { 'internalError' : string } |
  { 'invalidLength' : null } |
  { 'success' : null } |
  { 'invalidCharacters' : null };
export interface Weapon {
  'name' : string,
  'defenseBonus' : bigint,
  'attackBonus' : bigint,
  'description' : string,
  'magicBonus' : bigint,
  'speedBonus' : bigint,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'attackBot' : ActorMethod<[], BotCombatStatus>,
  'checkUsername' : ActorMethod<[string], UsernameUpdateResult>,
  'clickAura' : ActorMethod<[], undefined>,
  'createAdminPanelEvent' : ActorMethod<[string, string, bigint], undefined>,
  'createAnnouncement' : ActorMethod<[string, string], undefined>,
  'createPlayerProfile' : ActorMethod<[], undefined>,
  'followUser' : ActorMethod<[Principal], undefined>,
  'getAdminPanelEventsForCaller' : ActorMethod<[], Array<AdminPanelEvent>>,
  'getAdminPanelEventsForUser' : ActorMethod<
    [Principal],
    Array<AdminPanelEvent>
  >,
  'getAllAnnouncements' : ActorMethod<[], Array<Announcement>>,
  'getAllBots' : ActorMethod<[], Array<Bot>>,
  'getAllShopItems' : ActorMethod<[], Array<ShopItem>>,
  'getAnnouncement' : ActorMethod<[bigint], [] | [Announcement]>,
  'getBot' : ActorMethod<[bigint], [] | [Bot]>,
  'getBotCombatStatus' : ActorMethod<[], [] | [BotCombatStatus]>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCallerUsername' : ActorMethod<[], [] | [string]>,
  'getCallersFriends' : ActorMethod<[], Array<Principal>>,
  'getPrincipalForUsername' : ActorMethod<[string], [] | [Principal]>,
  'getShopItem' : ActorMethod<[bigint], [] | [ShopItem]>,
  'getUserAdminPanelEvent' : ActorMethod<
    [Principal, bigint],
    [] | [AdminPanelEvent]
  >,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getUsernameForPrincipal' : ActorMethod<[Principal], [] | [string]>,
  'getUsersFriends' : ActorMethod<[Principal], Array<Principal>>,
  'getWhoCallerFollowing' : ActorMethod<[], Array<Principal>>,
  'getWhoIsFollowingCaller' : ActorMethod<[], Array<Principal>>,
  'getWhoIsFollowingUser' : ActorMethod<[Principal], Array<Principal>>,
  'getWhoUserIsFollowing' : ActorMethod<[Principal], Array<Principal>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'profileExists' : ActorMethod<[], boolean>,
  'purchaseAdminPanel' : ActorMethod<[], undefined>,
  'purchaseShopItem' : ActorMethod<[bigint], undefined>,
  'rebirth' : ActorMethod<[], undefined>,
  'setUsername' : ActorMethod<[string], UsernameUpdateResult>,
  'startBotCombat' : ActorMethod<[bigint], BotCombatStatus>,
  'unfollowUser' : ActorMethod<[Principal], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];