/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Survivor = IDL.Record({
  'name' : IDL.Text,
  'level' : IDL.Nat,
  'experience' : IDL.Nat,
  'stats' : IDL.Record({
    'magic' : IDL.Nat,
    'level' : IDL.Nat,
    'speed' : IDL.Nat,
    'defense' : IDL.Nat,
    'attack' : IDL.Nat,
    'health' : IDL.Nat,
  }),
});
export const BotCombatStatus = IDL.Record({
  'combatOngoing' : IDL.Bool,
  'botName' : IDL.Text,
  'botHealth' : IDL.Nat,
  'botId' : IDL.Nat,
  'playerHealth' : IDL.Nat,
  'playerActiveSurvivor' : Survivor,
});
export const AdminPanelEvent = IDL.Record({
  'id' : IDL.Nat,
  'creator' : IDL.Principal,
  'description' : IDL.Text,
  'timestamp' : IDL.Nat,
  'eventName' : IDL.Text,
});
export const Announcement = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'createdBy' : IDL.Principal,
  'message' : IDL.Text,
  'timestamp' : IDL.Nat,
});
export const Bot = IDL.Record({
  'id' : IDL.Nat,
  'url' : IDL.Text,
  'rewardCurrency' : IDL.Nat,
  'difficulty' : IDL.Nat,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'rewardExp' : IDL.Nat,
});
export const Stat = IDL.Variant({
  'magic' : IDL.Nat,
  'level' : IDL.Nat,
  'experience' : IDL.Nat,
  'speed' : IDL.Nat,
  'defense' : IDL.Nat,
  'attack' : IDL.Nat,
  'health' : IDL.Nat,
});
export const ItemType = IDL.Variant({
  'key' : IDL.Null,
  'pet' : IDL.Null,
  'armor' : IDL.Null,
  'misc' : IDL.Null,
  'currencyPack' : IDL.Null,
  'weapon' : IDL.Null,
});
export const ShopItem = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'bonusStat' : IDL.Opt(Stat),
  'itemType' : ItemType,
  'price' : IDL.Nat,
});
export const Pet = IDL.Record({
  'dropRateBonus' : IDL.Int,
  'name' : IDL.Text,
  'experienceBonus' : IDL.Int,
  'description' : IDL.Text,
  'levelBonus' : IDL.Int,
});
export const Killer = IDL.Record({
  'id' : IDL.Nat,
  'url' : IDL.Text,
  'storyline' : IDL.Opt(IDL.Text),
  'name' : IDL.Text,
  'unlocked' : IDL.Bool,
  'description' : IDL.Text,
  'stats' : IDL.Record({
    'magic' : IDL.Nat,
    'level' : IDL.Nat,
    'speed' : IDL.Nat,
    'defense' : IDL.Nat,
    'attack' : IDL.Nat,
    'health' : IDL.Nat,
  }),
  'unlockCriteria' : IDL.Opt(IDL.Nat),
});
export const Weapon = IDL.Record({
  'name' : IDL.Text,
  'defenseBonus' : IDL.Int,
  'attackBonus' : IDL.Int,
  'description' : IDL.Text,
  'magicBonus' : IDL.Int,
  'speedBonus' : IDL.Int,
});
export const UserProfile = IDL.Record({
  'hasAdminPanel' : IDL.Bool,
  'completedQuests' : IDL.Vec(IDL.Nat),
  'storylineProgress' : IDL.Nat,
  'activeDungeonId' : IDL.Opt(IDL.Nat),
  'inventory' : IDL.Vec(IDL.Text),
  'pets' : IDL.Vec(Pet),
  'collectedKeys' : IDL.Vec(IDL.Text),
  'survivors' : IDL.Vec(Survivor),
  'activeSurvivor' : IDL.Opt(Survivor),
  'currency' : IDL.Nat,
  'equippedArmor' : IDL.Opt(IDL.Nat),
  'killers' : IDL.Vec(Killer),
  'weapons' : IDL.Vec(Weapon),
  'openedCrates' : IDL.Vec(IDL.Nat),
  'equippedWeapon' : IDL.Opt(Weapon),
  'equippedPet' : IDL.Opt(Pet),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'attackBot' : IDL.Func([], [BotCombatStatus], []),
  'createAdminPanelEvent' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat], [], []),
  'createAnnouncement' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'followUser' : IDL.Func([IDL.Principal], [], []),
  'getAdminPanelEventsForCaller' : IDL.Func(
      [],
      [IDL.Vec(AdminPanelEvent)],
      ['query'],
    ),
  'getAdminPanelEventsForUser' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(AdminPanelEvent)],
      ['query'],
    ),
  'getAllAnnouncements' : IDL.Func([], [IDL.Vec(Announcement)], ['query']),
  'getAllBots' : IDL.Func([], [IDL.Vec(Bot)], ['query']),
  'getAllShopItems' : IDL.Func([], [IDL.Vec(ShopItem)], ['query']),
  'getAnnouncement' : IDL.Func([IDL.Nat], [IDL.Opt(Announcement)], ['query']),
  'getBot' : IDL.Func([IDL.Nat], [IDL.Opt(Bot)], ['query']),
  'getBotCombatStatus' : IDL.Func([], [IDL.Opt(BotCombatStatus)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCallersFriends' : IDL.Func([], [IDL.Vec(IDL.Principal)], ['query']),
  'getShopItem' : IDL.Func([IDL.Nat], [IDL.Opt(ShopItem)], ['query']),
  'getUserAdminPanelEvent' : IDL.Func(
      [IDL.Principal, IDL.Nat],
      [IDL.Opt(AdminPanelEvent)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getUsersFriends' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(IDL.Principal)],
      ['query'],
    ),
  'getWhoCallerFollowing' : IDL.Func([], [IDL.Vec(IDL.Principal)], ['query']),
  'getWhoIsFollowingCaller' : IDL.Func([], [IDL.Vec(IDL.Principal)], ['query']),
  'getWhoIsFollowingUser' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(IDL.Principal)],
      ['query'],
    ),
  'getWhoUserIsFollowing' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(IDL.Principal)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'purchaseAdminPanel' : IDL.Func([], [], []),
  'purchaseShopItem' : IDL.Func([IDL.Nat], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'startBotCombat' : IDL.Func([IDL.Nat], [BotCombatStatus], []),
  'unfollowUser' : IDL.Func([IDL.Principal], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Survivor = IDL.Record({
    'name' : IDL.Text,
    'level' : IDL.Nat,
    'experience' : IDL.Nat,
    'stats' : IDL.Record({
      'magic' : IDL.Nat,
      'level' : IDL.Nat,
      'speed' : IDL.Nat,
      'defense' : IDL.Nat,
      'attack' : IDL.Nat,
      'health' : IDL.Nat,
    }),
  });
  const BotCombatStatus = IDL.Record({
    'combatOngoing' : IDL.Bool,
    'botName' : IDL.Text,
    'botHealth' : IDL.Nat,
    'botId' : IDL.Nat,
    'playerHealth' : IDL.Nat,
    'playerActiveSurvivor' : Survivor,
  });
  const AdminPanelEvent = IDL.Record({
    'id' : IDL.Nat,
    'creator' : IDL.Principal,
    'description' : IDL.Text,
    'timestamp' : IDL.Nat,
    'eventName' : IDL.Text,
  });
  const Announcement = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'createdBy' : IDL.Principal,
    'message' : IDL.Text,
    'timestamp' : IDL.Nat,
  });
  const Bot = IDL.Record({
    'id' : IDL.Nat,
    'url' : IDL.Text,
    'rewardCurrency' : IDL.Nat,
    'difficulty' : IDL.Nat,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'rewardExp' : IDL.Nat,
  });
  const Stat = IDL.Variant({
    'magic' : IDL.Nat,
    'level' : IDL.Nat,
    'experience' : IDL.Nat,
    'speed' : IDL.Nat,
    'defense' : IDL.Nat,
    'attack' : IDL.Nat,
    'health' : IDL.Nat,
  });
  const ItemType = IDL.Variant({
    'key' : IDL.Null,
    'pet' : IDL.Null,
    'armor' : IDL.Null,
    'misc' : IDL.Null,
    'currencyPack' : IDL.Null,
    'weapon' : IDL.Null,
  });
  const ShopItem = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'bonusStat' : IDL.Opt(Stat),
    'itemType' : ItemType,
    'price' : IDL.Nat,
  });
  const Pet = IDL.Record({
    'dropRateBonus' : IDL.Int,
    'name' : IDL.Text,
    'experienceBonus' : IDL.Int,
    'description' : IDL.Text,
    'levelBonus' : IDL.Int,
  });
  const Killer = IDL.Record({
    'id' : IDL.Nat,
    'url' : IDL.Text,
    'storyline' : IDL.Opt(IDL.Text),
    'name' : IDL.Text,
    'unlocked' : IDL.Bool,
    'description' : IDL.Text,
    'stats' : IDL.Record({
      'magic' : IDL.Nat,
      'level' : IDL.Nat,
      'speed' : IDL.Nat,
      'defense' : IDL.Nat,
      'attack' : IDL.Nat,
      'health' : IDL.Nat,
    }),
    'unlockCriteria' : IDL.Opt(IDL.Nat),
  });
  const Weapon = IDL.Record({
    'name' : IDL.Text,
    'defenseBonus' : IDL.Int,
    'attackBonus' : IDL.Int,
    'description' : IDL.Text,
    'magicBonus' : IDL.Int,
    'speedBonus' : IDL.Int,
  });
  const UserProfile = IDL.Record({
    'hasAdminPanel' : IDL.Bool,
    'completedQuests' : IDL.Vec(IDL.Nat),
    'storylineProgress' : IDL.Nat,
    'activeDungeonId' : IDL.Opt(IDL.Nat),
    'inventory' : IDL.Vec(IDL.Text),
    'pets' : IDL.Vec(Pet),
    'collectedKeys' : IDL.Vec(IDL.Text),
    'survivors' : IDL.Vec(Survivor),
    'activeSurvivor' : IDL.Opt(Survivor),
    'currency' : IDL.Nat,
    'equippedArmor' : IDL.Opt(IDL.Nat),
    'killers' : IDL.Vec(Killer),
    'weapons' : IDL.Vec(Weapon),
    'openedCrates' : IDL.Vec(IDL.Nat),
    'equippedWeapon' : IDL.Opt(Weapon),
    'equippedPet' : IDL.Opt(Pet),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'attackBot' : IDL.Func([], [BotCombatStatus], []),
    'createAdminPanelEvent' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat], [], []),
    'createAnnouncement' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'followUser' : IDL.Func([IDL.Principal], [], []),
    'getAdminPanelEventsForCaller' : IDL.Func(
        [],
        [IDL.Vec(AdminPanelEvent)],
        ['query'],
      ),
    'getAdminPanelEventsForUser' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(AdminPanelEvent)],
        ['query'],
      ),
    'getAllAnnouncements' : IDL.Func([], [IDL.Vec(Announcement)], ['query']),
    'getAllBots' : IDL.Func([], [IDL.Vec(Bot)], ['query']),
    'getAllShopItems' : IDL.Func([], [IDL.Vec(ShopItem)], ['query']),
    'getAnnouncement' : IDL.Func([IDL.Nat], [IDL.Opt(Announcement)], ['query']),
    'getBot' : IDL.Func([IDL.Nat], [IDL.Opt(Bot)], ['query']),
    'getBotCombatStatus' : IDL.Func([], [IDL.Opt(BotCombatStatus)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCallersFriends' : IDL.Func([], [IDL.Vec(IDL.Principal)], ['query']),
    'getShopItem' : IDL.Func([IDL.Nat], [IDL.Opt(ShopItem)], ['query']),
    'getUserAdminPanelEvent' : IDL.Func(
        [IDL.Principal, IDL.Nat],
        [IDL.Opt(AdminPanelEvent)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getUsersFriends' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(IDL.Principal)],
        ['query'],
      ),
    'getWhoCallerFollowing' : IDL.Func([], [IDL.Vec(IDL.Principal)], ['query']),
    'getWhoIsFollowingCaller' : IDL.Func(
        [],
        [IDL.Vec(IDL.Principal)],
        ['query'],
      ),
    'getWhoIsFollowingUser' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(IDL.Principal)],
        ['query'],
      ),
    'getWhoUserIsFollowing' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(IDL.Principal)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'purchaseAdminPanel' : IDL.Func([], [], []),
    'purchaseShopItem' : IDL.Func([IDL.Nat], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'startBotCombat' : IDL.Func([IDL.Nat], [BotCombatStatus], []),
    'unfollowUser' : IDL.Func([IDL.Principal], [], []),
  });
};

export const init = ({ IDL }) => { return []; };