/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AdminPanelEvent {
  'id' : bigint,
  'creator' : Principal,
  'description' : string,
  'timestamp' : bigint,
  'eventName' : string,
}
export interface Killer {
  'id' : bigint,
  'url' : string,
  'storyline' : [] | [string],
  'name' : string,
  'unlocked' : boolean,
  'description' : string,
  'stats' : {
    'magic' : bigint,
    'level' : bigint,
    'speed' : bigint,
    'defense' : bigint,
    'attack' : bigint,
    'health' : bigint,
  },
  'unlockCriteria' : [] | [bigint],
}
export interface Pet {
  'dropRateBonus' : bigint,
  'name' : string,
  'experienceBonus' : bigint,
  'description' : string,
  'levelBonus' : bigint,
}
export interface Survivor {
  'name' : string,
  'level' : bigint,
  'experience' : bigint,
  'stats' : {
    'magic' : bigint,
    'level' : bigint,
    'speed' : bigint,
    'defense' : bigint,
    'attack' : bigint,
    'health' : bigint,
  },
}
export interface UserProfile {
  'hasAdminPanel' : boolean,
  'completedQuests' : Array<bigint>,
  'storylineProgress' : bigint,
  'activeDungeonId' : [] | [bigint],
  'inventory' : Array<string>,
  'pets' : Array<Pet>,
  'collectedKeys' : Array<string>,
  'survivors' : Array<Survivor>,
  'activeSurvivor' : [] | [Survivor],
  'currency' : bigint,
  'equippedArmor' : [] | [bigint],
  'killers' : Array<Killer>,
  'weapons' : Array<Weapon>,
  'openedCrates' : Array<bigint>,
  'equippedWeapon' : [] | [Weapon],
  'equippedPet' : [] | [Pet],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface Weapon {
  'name' : string,
  'defenseBonus' : bigint,
  'attackBonus' : bigint,
  'description' : string,
  'magicBonus' : bigint,
  'speedBonus' : bigint,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createAdminPanelEvent' : ActorMethod<[string, string, bigint], undefined>,
  'followUser' : ActorMethod<[Principal], undefined>,
  'getAdminPanelEventsForCaller' : ActorMethod<[], Array<AdminPanelEvent>>,
  'getAdminPanelEventsForUser' : ActorMethod<
    [Principal],
    Array<AdminPanelEvent>
  >,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCallersFriends' : ActorMethod<[], Array<Principal>>,
  'getUserAdminPanelEvent' : ActorMethod<
    [Principal, bigint],
    [] | [AdminPanelEvent]
  >,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getUsersFriends' : ActorMethod<[Principal], Array<Principal>>,
  'getWhoCallerFollowing' : ActorMethod<[], Array<Principal>>,
  'getWhoIsFollowingCaller' : ActorMethod<[], Array<Principal>>,
  'getWhoIsFollowingUser' : ActorMethod<[Principal], Array<Principal>>,
  'getWhoUserIsFollowing' : ActorMethod<[Principal], Array<Principal>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'purchaseAdminPanel' : ActorMethod<[], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'unfollowUser' : ActorMethod<[Principal], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];