/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface WhyDontYouJoin {
    id: bigint;
    active: boolean;
    name: string;
    memberCount: bigint;
    createClan: boolean;
    description: string;
    imageUrl: string;
    leader: Principal;
}
export interface CombatDetails {
    status: CombatStatus;
    result?: CombatResult;
    enemyStats: Enemy;
    playerStats: Survivor;
    rewardedCurrency: bigint;
    enemyHealth: bigint;
    rewardedExp: bigint;
    playerHealth: bigint;
}
export interface PlayerProfile {
    hasAdminPanel: boolean;
    completedQuests: Array<bigint>;
    storylineProgress: bigint;
    activeDungeonId?: bigint;
    inventory: Array<string>;
    pets: Array<Pet>;
    collectedKeys: Array<string>;
    survivors: Array<Survivor>;
    activeSurvivor?: Survivor;
    currency: bigint;
    equippedArmor?: bigint;
    killers: Array<Killer>;
    weapons: Array<Weapon>;
    openedCrates: Array<bigint>;
    equippedWeapon?: Weapon;
    equippedPet?: Pet;
}
export interface Killer {
    id: bigint;
    url: string;
    storyline?: string;
    name: string;
    unlocked: boolean;
    description: string;
    stats: {
        magic: bigint;
        level: bigint;
        speed: bigint;
        defense: bigint;
        attack: bigint;
        health: bigint;
    };
    unlockCriteria?: bigint;
}
export interface Dungeon {
    id: bigint;
    difficulty: bigint;
    name: string;
    description: string;
    availableCrates: Array<Crate>;
    quests: Array<Quest>;
}
export interface Crate {
    id: bigint;
    reward: bigint;
    name: string;
    description: string;
    requiredKey: string;
    location: string;
}
export interface Clan {
    id: bigint;
    members: Array<Principal>;
    name: string;
    createdAt: bigint;
    memberCount: bigint;
    founder: Principal;
}
export interface Survivor {
    name: string;
    level: bigint;
    experience: bigint;
    stats: {
        magic: bigint;
        level: bigint;
        speed: bigint;
        defense: bigint;
        attack: bigint;
        health: bigint;
    };
}
export interface Pet {
    dropRateBonus: bigint;
    name: string;
    experienceBonus: bigint;
    description: string;
    levelBonus: bigint;
}
export interface Enemy {
    magic: bigint;
    name: string;
    goldReward: bigint;
    expReward: bigint;
    speed: bigint;
    defense: bigint;
    attack: bigint;
    health: bigint;
}
export interface Weapon {
    name: string;
    defenseBonus: bigint;
    attackBonus: bigint;
    description: string;
    magicBonus: bigint;
    speedBonus: bigint;
}
export interface Quest {
    id: bigint;
    dungeonId: bigint;
    rewardCurrency: bigint;
    name: string;
    description: string;
}
export interface CombatResult {
    rewardCurrency: bigint;
    winner: Winner;
    rewardExp: bigint;
}
export interface CombatStatus {
    combatOngoing: boolean;
    enemyName: string;
    enemyHealth: bigint;
    playerHealth: bigint;
    playerActiveSurvivor: Survivor;
}
export interface UserProfile {
    hasAdminPanel: boolean;
    completedQuests: Array<bigint>;
    storylineProgress: bigint;
    activeDungeonId?: bigint;
    inventory: Array<string>;
    pets: Array<Pet>;
    collectedKeys: Array<string>;
    survivors: Array<Survivor>;
    activeSurvivor?: Survivor;
    currency: bigint;
    equippedArmor?: bigint;
    killers: Array<Killer>;
    weapons: Array<Weapon>;
    openedCrates: Array<bigint>;
    equippedWeapon?: Weapon;
    equippedPet?: Pet;
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum Winner {
    player = "player",
    enemy = "enemy"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addPet(pet: Pet): Promise<void>;
    addWeapon(weapon: Weapon): Promise<void>;
    addWhyDontYouJoin(name: string, description: string, imageUrl: string): Promise<WhyDontYouJoin>;
    adminGrantCurrency(amount: bigint): Promise<void>;
    adminSetLevel(survivorName: string, newLevel: bigint): Promise<void>;
    adminUnlockKiller(killerId: bigint): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    completeQuest(questId: bigint): Promise<void>;
    createClanFromJoin(whyJoinId: bigint, clanName: string): Promise<Clan | null>;
    createPlayerProfile(): Promise<PlayerProfile>;
    createSurvivor(name: string, startingStats: {
        magic: bigint;
        speed: bigint;
        defense: bigint;
        attack: bigint;
        health: bigint;
    }): Promise<void>;
    earnCurrency(amount: bigint): Promise<void>;
    equipPet(petName: string): Promise<void>;
    equipWeapon(weaponName: string): Promise<void>;
    getActiveDungeon(): Promise<bigint | null>;
    getActiveDungeonMaps(): Promise<Array<Dungeon>>;
    getActiveWhyDontYouJoins(): Promise<Array<WhyDontYouJoin>>;
    getAllDungeonKeys(): Promise<Array<string>>;
    getAllDungeonMaps(): Promise<Array<Dungeon>>;
    getAllKeys(): Promise<Array<string>>;
    getAllWhyDontYouJoins(): Promise<Array<WhyDontYouJoin>>;
    getAvailableDungeonMaps(): Promise<Array<Dungeon> | null>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getClanMarketplace(): Promise<Array<Clan>>;
    getCollectedKeys(): Promise<Array<string>>;
    getCombatStatus(): Promise<CombatStatus | null>;
    getCompletedQuests(): Promise<Array<bigint>>;
    getOpenedCrates(): Promise<Array<bigint>>;
    getPlayerInventory(): Promise<Array<string>>;
    getPlayerProfile(): Promise<PlayerProfile>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    joinExistingClan(clanId: bigint): Promise<Clan | null>;
    joinRandomClan(): Promise<Clan | null>;
    performAttack(enemy: Enemy): Promise<CombatDetails>;
    performMagicAttack(_enemy: Enemy): Promise<CombatDetails>;
    purchaseAdminPanel(): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    setActiveSurvivor(survivorName: string): Promise<void>;
    startCombat(enemy: Enemy): Promise<void>;
    startQuest(questId: bigint): Promise<void>;
    unlockCrate(crateId: bigint): Promise<void>;
    unlockNextKiller(): Promise<void>;
    updateWhyDontYouJoin(id: bigint, active: boolean): Promise<WhyDontYouJoin | null>;
}
import type { Clan as _Clan, CombatDetails as _CombatDetails, CombatResult as _CombatResult, CombatStatus as _CombatStatus, Dungeon as _Dungeon, Enemy as _Enemy, Killer as _Killer, Pet as _Pet, PlayerProfile as _PlayerProfile, Survivor as _Survivor, UserProfile as _UserProfile, UserRole as _UserRole, Weapon as _Weapon, WhyDontYouJoin as _WhyDontYouJoin, Winner as _Winner } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addPet(arg0: Pet): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addPet(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addPet(arg0);
            return result;
        }
    }
    async addWeapon(arg0: Weapon): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addWeapon(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addWeapon(arg0);
            return result;
        }
    }
    async addWhyDontYouJoin(arg0: string, arg1: string, arg2: string): Promise<WhyDontYouJoin> {
        if (this.processError) {
            try {
                const result = await this.actor.addWhyDontYouJoin(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addWhyDontYouJoin(arg0, arg1, arg2);
            return result;
        }
    }
    async adminGrantCurrency(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.adminGrantCurrency(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminGrantCurrency(arg0);
            return result;
        }
    }
    async adminSetLevel(arg0: string, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.adminSetLevel(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminSetLevel(arg0, arg1);
            return result;
        }
    }
    async adminUnlockKiller(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.adminUnlockKiller(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminUnlockKiller(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async completeQuest(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.completeQuest(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.completeQuest(arg0);
            return result;
        }
    }
    async createClanFromJoin(arg0: bigint, arg1: string): Promise<Clan | null> {
        if (this.processError) {
            try {
                const result = await this.actor.createClanFromJoin(arg0, arg1);
                return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createClanFromJoin(arg0, arg1);
            return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async createPlayerProfile(): Promise<PlayerProfile> {
        if (this.processError) {
            try {
                const result = await this.actor.createPlayerProfile();
                return from_candid_PlayerProfile_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createPlayerProfile();
            return from_candid_PlayerProfile_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async createSurvivor(arg0: string, arg1: {
        magic: bigint;
        speed: bigint;
        defense: bigint;
        attack: bigint;
        health: bigint;
    }): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createSurvivor(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createSurvivor(arg0, arg1);
            return result;
        }
    }
    async earnCurrency(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.earnCurrency(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.earnCurrency(arg0);
            return result;
        }
    }
    async equipPet(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.equipPet(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.equipPet(arg0);
            return result;
        }
    }
    async equipWeapon(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.equipWeapon(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.equipWeapon(arg0);
            return result;
        }
    }
    async getActiveDungeon(): Promise<bigint | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getActiveDungeon();
                return from_candid_opt_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getActiveDungeon();
            return from_candid_opt_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async getActiveDungeonMaps(): Promise<Array<Dungeon>> {
        if (this.processError) {
            try {
                const result = await this.actor.getActiveDungeonMaps();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getActiveDungeonMaps();
            return result;
        }
    }
    async getActiveWhyDontYouJoins(): Promise<Array<WhyDontYouJoin>> {
        if (this.processError) {
            try {
                const result = await this.actor.getActiveWhyDontYouJoins();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getActiveWhyDontYouJoins();
            return result;
        }
    }
    async getAllDungeonKeys(): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllDungeonKeys();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllDungeonKeys();
            return result;
        }
    }
    async getAllDungeonMaps(): Promise<Array<Dungeon>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllDungeonMaps();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllDungeonMaps();
            return result;
        }
    }
    async getAllKeys(): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllKeys();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllKeys();
            return result;
        }
    }
    async getAllWhyDontYouJoins(): Promise<Array<WhyDontYouJoin>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllWhyDontYouJoins();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllWhyDontYouJoins();
            return result;
        }
    }
    async getAvailableDungeonMaps(): Promise<Array<Dungeon> | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getAvailableDungeonMaps();
                return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAvailableDungeonMaps();
            return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getClanMarketplace(): Promise<Array<Clan>> {
        if (this.processError) {
            try {
                const result = await this.actor.getClanMarketplace();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getClanMarketplace();
            return result;
        }
    }
    async getCollectedKeys(): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCollectedKeys();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCollectedKeys();
            return result;
        }
    }
    async getCombatStatus(): Promise<CombatStatus | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCombatStatus();
                return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCombatStatus();
            return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCompletedQuests(): Promise<Array<bigint>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCompletedQuests();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCompletedQuests();
            return result;
        }
    }
    async getOpenedCrates(): Promise<Array<bigint>> {
        if (this.processError) {
            try {
                const result = await this.actor.getOpenedCrates();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOpenedCrates();
            return result;
        }
    }
    async getPlayerInventory(): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPlayerInventory();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPlayerInventory();
            return result;
        }
    }
    async getPlayerProfile(): Promise<PlayerProfile> {
        if (this.processError) {
            try {
                const result = await this.actor.getPlayerProfile();
                return from_candid_PlayerProfile_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPlayerProfile();
            return from_candid_PlayerProfile_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async joinExistingClan(arg0: bigint): Promise<Clan | null> {
        if (this.processError) {
            try {
                const result = await this.actor.joinExistingClan(arg0);
                return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.joinExistingClan(arg0);
            return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async joinRandomClan(): Promise<Clan | null> {
        if (this.processError) {
            try {
                const result = await this.actor.joinRandomClan();
                return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.joinRandomClan();
            return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async performAttack(arg0: Enemy): Promise<CombatDetails> {
        if (this.processError) {
            try {
                const result = await this.actor.performAttack(arg0);
                return from_candid_CombatDetails_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.performAttack(arg0);
            return from_candid_CombatDetails_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async performMagicAttack(arg0: Enemy): Promise<CombatDetails> {
        if (this.processError) {
            try {
                const result = await this.actor.performMagicAttack(arg0);
                return from_candid_CombatDetails_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.performMagicAttack(arg0);
            return from_candid_CombatDetails_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async purchaseAdminPanel(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.purchaseAdminPanel();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.purchaseAdminPanel();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n27(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n27(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async setActiveSurvivor(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setActiveSurvivor(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setActiveSurvivor(arg0);
            return result;
        }
    }
    async startCombat(arg0: Enemy): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.startCombat(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.startCombat(arg0);
            return result;
        }
    }
    async startQuest(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.startQuest(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.startQuest(arg0);
            return result;
        }
    }
    async unlockCrate(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.unlockCrate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.unlockCrate(arg0);
            return result;
        }
    }
    async unlockNextKiller(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.unlockNextKiller();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.unlockNextKiller();
            return result;
        }
    }
    async updateWhyDontYouJoin(arg0: bigint, arg1: boolean): Promise<WhyDontYouJoin | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updateWhyDontYouJoin(arg0, arg1);
                return from_candid_opt_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateWhyDontYouJoin(arg0, arg1);
            return from_candid_opt_n32(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_CombatDetails_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CombatDetails): CombatDetails {
    return from_candid_record_n21(_uploadFile, _downloadFile, value);
}
function from_candid_CombatResult_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CombatResult): CombatResult {
    return from_candid_record_n24(_uploadFile, _downloadFile, value);
}
function from_candid_Killer_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Killer): Killer {
    return from_candid_record_n10(_uploadFile, _downloadFile, value);
}
function from_candid_PlayerProfile_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PlayerProfile): PlayerProfile {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n18(_uploadFile, _downloadFile, value);
}
function from_candid_Winner_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Winner): Winner {
    return from_candid_variant_n26(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Weapon]): Weapon | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Pet]): Pet | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Array<_Dungeon>]): Array<Dungeon> | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n16(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_CombatStatus]): CombatStatus | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_CombatResult]): CombatResult | null {
    return value.length === 0 ? null : from_candid_CombatResult_n23(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Clan]): Clan | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_WhyDontYouJoin]): WhyDontYouJoin | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Survivor]): Survivor | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    url: string;
    storyline: [] | [string];
    name: string;
    unlocked: boolean;
    description: string;
    stats: {
        magic: bigint;
        level: bigint;
        speed: bigint;
        defense: bigint;
        attack: bigint;
        health: bigint;
    };
    unlockCriteria: [] | [bigint];
}): {
    id: bigint;
    url: string;
    storyline?: string;
    name: string;
    unlocked: boolean;
    description: string;
    stats: {
        magic: bigint;
        level: bigint;
        speed: bigint;
        defense: bigint;
        attack: bigint;
        health: bigint;
    };
    unlockCriteria?: bigint;
} {
    return {
        id: value.id,
        url: value.url,
        storyline: record_opt_to_undefined(from_candid_opt_n11(_uploadFile, _downloadFile, value.storyline)),
        name: value.name,
        unlocked: value.unlocked,
        description: value.description,
        stats: value.stats,
        unlockCriteria: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.unlockCriteria))
    };
}
function from_candid_record_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _CombatStatus;
    result: [] | [_CombatResult];
    enemyStats: _Enemy;
    playerStats: _Survivor;
    rewardedCurrency: bigint;
    enemyHealth: bigint;
    rewardedExp: bigint;
    playerHealth: bigint;
}): {
    status: CombatStatus;
    result?: CombatResult;
    enemyStats: Enemy;
    playerStats: Survivor;
    rewardedCurrency: bigint;
    enemyHealth: bigint;
    rewardedExp: bigint;
    playerHealth: bigint;
} {
    return {
        status: value.status,
        result: record_opt_to_undefined(from_candid_opt_n22(_uploadFile, _downloadFile, value.result)),
        enemyStats: value.enemyStats,
        playerStats: value.playerStats,
        rewardedCurrency: value.rewardedCurrency,
        enemyHealth: value.enemyHealth,
        rewardedExp: value.rewardedExp,
        playerHealth: value.playerHealth
    };
}
function from_candid_record_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    rewardCurrency: bigint;
    winner: _Winner;
    rewardExp: bigint;
}): {
    rewardCurrency: bigint;
    winner: Winner;
    rewardExp: bigint;
} {
    return {
        rewardCurrency: value.rewardCurrency,
        winner: from_candid_Winner_n25(_uploadFile, _downloadFile, value.winner),
        rewardExp: value.rewardExp
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    hasAdminPanel: boolean;
    completedQuests: Array<bigint>;
    storylineProgress: bigint;
    activeDungeonId: [] | [bigint];
    inventory: Array<string>;
    pets: Array<_Pet>;
    collectedKeys: Array<string>;
    survivors: Array<_Survivor>;
    activeSurvivor: [] | [_Survivor];
    currency: bigint;
    equippedArmor: [] | [bigint];
    killers: Array<_Killer>;
    weapons: Array<_Weapon>;
    openedCrates: Array<bigint>;
    equippedWeapon: [] | [_Weapon];
    equippedPet: [] | [_Pet];
}): {
    hasAdminPanel: boolean;
    completedQuests: Array<bigint>;
    storylineProgress: bigint;
    activeDungeonId?: bigint;
    inventory: Array<string>;
    pets: Array<Pet>;
    collectedKeys: Array<string>;
    survivors: Array<Survivor>;
    activeSurvivor?: Survivor;
    currency: bigint;
    equippedArmor?: bigint;
    killers: Array<Killer>;
    weapons: Array<Weapon>;
    openedCrates: Array<bigint>;
    equippedWeapon?: Weapon;
    equippedPet?: Pet;
} {
    return {
        hasAdminPanel: value.hasAdminPanel,
        completedQuests: value.completedQuests,
        storylineProgress: value.storylineProgress,
        activeDungeonId: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.activeDungeonId)),
        inventory: value.inventory,
        pets: value.pets,
        collectedKeys: value.collectedKeys,
        survivors: value.survivors,
        activeSurvivor: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.activeSurvivor)),
        currency: value.currency,
        equippedArmor: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.equippedArmor)),
        killers: from_candid_vec_n8(_uploadFile, _downloadFile, value.killers),
        weapons: value.weapons,
        openedCrates: value.openedCrates,
        equippedWeapon: record_opt_to_undefined(from_candid_opt_n12(_uploadFile, _downloadFile, value.equippedWeapon)),
        equippedPet: record_opt_to_undefined(from_candid_opt_n13(_uploadFile, _downloadFile, value.equippedPet))
    };
}
function from_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    player: null;
} | {
    enemy: null;
}): Winner {
    return "player" in value ? Winner.player : "enemy" in value ? Winner.enemy : value;
}
function from_candid_vec_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Killer>): Array<Killer> {
    return value.map((x)=>from_candid_Killer_n9(_uploadFile, _downloadFile, x));
}
function to_candid_Killer_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Killer): _Killer {
    return to_candid_record_n31(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n28(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_record_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    hasAdminPanel: boolean;
    completedQuests: Array<bigint>;
    storylineProgress: bigint;
    activeDungeonId?: bigint;
    inventory: Array<string>;
    pets: Array<Pet>;
    collectedKeys: Array<string>;
    survivors: Array<Survivor>;
    activeSurvivor?: Survivor;
    currency: bigint;
    equippedArmor?: bigint;
    killers: Array<Killer>;
    weapons: Array<Weapon>;
    openedCrates: Array<bigint>;
    equippedWeapon?: Weapon;
    equippedPet?: Pet;
}): {
    hasAdminPanel: boolean;
    completedQuests: Array<bigint>;
    storylineProgress: bigint;
    activeDungeonId: [] | [bigint];
    inventory: Array<string>;
    pets: Array<_Pet>;
    collectedKeys: Array<string>;
    survivors: Array<_Survivor>;
    activeSurvivor: [] | [_Survivor];
    currency: bigint;
    equippedArmor: [] | [bigint];
    killers: Array<_Killer>;
    weapons: Array<_Weapon>;
    openedCrates: Array<bigint>;
    equippedWeapon: [] | [_Weapon];
    equippedPet: [] | [_Pet];
} {
    return {
        hasAdminPanel: value.hasAdminPanel,
        completedQuests: value.completedQuests,
        storylineProgress: value.storylineProgress,
        activeDungeonId: value.activeDungeonId ? candid_some(value.activeDungeonId) : candid_none(),
        inventory: value.inventory,
        pets: value.pets,
        collectedKeys: value.collectedKeys,
        survivors: value.survivors,
        activeSurvivor: value.activeSurvivor ? candid_some(value.activeSurvivor) : candid_none(),
        currency: value.currency,
        equippedArmor: value.equippedArmor ? candid_some(value.equippedArmor) : candid_none(),
        killers: to_candid_vec_n29(_uploadFile, _downloadFile, value.killers),
        weapons: value.weapons,
        openedCrates: value.openedCrates,
        equippedWeapon: value.equippedWeapon ? candid_some(value.equippedWeapon) : candid_none(),
        equippedPet: value.equippedPet ? candid_some(value.equippedPet) : candid_none()
    };
}
function to_candid_record_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    url: string;
    storyline?: string;
    name: string;
    unlocked: boolean;
    description: string;
    stats: {
        magic: bigint;
        level: bigint;
        speed: bigint;
        defense: bigint;
        attack: bigint;
        health: bigint;
    };
    unlockCriteria?: bigint;
}): {
    id: bigint;
    url: string;
    storyline: [] | [string];
    name: string;
    unlocked: boolean;
    description: string;
    stats: {
        magic: bigint;
        level: bigint;
        speed: bigint;
        defense: bigint;
        attack: bigint;
        health: bigint;
    };
    unlockCriteria: [] | [bigint];
} {
    return {
        id: value.id,
        url: value.url,
        storyline: value.storyline ? candid_some(value.storyline) : candid_none(),
        name: value.name,
        unlocked: value.unlocked,
        description: value.description,
        stats: value.stats,
        unlockCriteria: value.unlockCriteria ? candid_some(value.unlockCriteria) : candid_none()
    };
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_vec_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<Killer>): Array<_Killer> {
    return value.map((x)=>to_candid_Killer_n30(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
